"""Fix typo in models.py

Revision ID: 2b1421e46110
Revises: ec433c400077
Create Date: 2020-06-08 10:50:19.327513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1421e46110'
down_revision = 'ec433c400077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('completion_status', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_project_completion_status'), 'project', ['completion_status'], unique=False)
    op.drop_index('ix_project_completetion_status', table_name='project')
    op.drop_column('project', 'completetion_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('completetion_status', sa.BOOLEAN(), nullable=True))
    op.create_index('ix_project_completetion_status', 'project', ['completetion_status'], unique=False)
    op.drop_index(op.f('ix_project_completion_status'), table_name='project')
    op.drop_column('project', 'completion_status')
    # ### end Alembic commands ###
