"""Replace demo_models with SWApp models

Revision ID: ec433c400077
Revises: 3d9fd2738bf8
Create Date: 2020-05-28 14:20:59.471727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec433c400077'
down_revision = '3d9fd2738bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exhibition_name', sa.String(length=64), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibition_exhibition_name'), 'exhibition', ['exhibition_name'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('exhibition_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('completetion_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibition.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_completetion_status'), 'project', ['completetion_status'], unique=False)
    op.create_index(op.f('ix_project_title'), 'project', ['title'], unique=False)
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('signer_id', sa.Integer(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['signer_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_checked'), 'stage', ['checked'], unique=False)
    op.create_index(op.f('ix_stage_name'), 'stage', ['name'], unique=True)
    op.create_index(op.f('ix_stage_timestamp'), 'stage', ['timestamp'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=64), nullable=True),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_student_name'), 'student', ['student_name'], unique=False)
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_teacher_name'), 'teacher', ['teacher_name'], unique=False)
    op.drop_index('ix_person_color', table_name='person')
    op.drop_index('ix_person_mod_time', table_name='person')
    op.drop_index('ix_person_username', table_name='person')
    op.drop_table('person')
    op.drop_index('ix_message_timestamp', table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('person_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_timestamp', 'message', ['timestamp'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('color', sa.VARCHAR(length=64), nullable=True),
    sa.Column('mod_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_person_username', 'person', ['username'], unique=1)
    op.create_index('ix_person_mod_time', 'person', ['mod_time'], unique=False)
    op.create_index('ix_person_color', 'person', ['color'], unique=False)
    op.drop_index(op.f('ix_teacher_teacher_name'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_student_student_name'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_stage_timestamp'), table_name='stage')
    op.drop_index(op.f('ix_stage_name'), table_name='stage')
    op.drop_index(op.f('ix_stage_checked'), table_name='stage')
    op.drop_table('stage')
    op.drop_index(op.f('ix_project_title'), table_name='project')
    op.drop_index(op.f('ix_project_completetion_status'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_exhibition_exhibition_name'), table_name='exhibition')
    op.drop_table('exhibition')
    # ### end Alembic commands ###
